package internal

import (
	"io"
	"strings"
)

type Generator struct {
	impl Implement
}

// generatedFileHeader is stable across go run temporary paths so golden tests
// and go:generate diffs stay readable.
const generatedFileHeader = `// Code generated by juicecli; DO NOT EDIT.`

func (g *Generator) Generate() (io.Reader, error) {
	builder := strings.Builder{}
	builder.WriteString(generatedFileHeader)
	builder.WriteString("\n\n")
	data, err := g.impl.Render()
	if err != nil {
		return nil, err
	}
	builder.WriteString(data)
	return strings.NewReader(builder.String()), nil
}

// WriteTo writes generated code to writer.
func (g *Generator) WriteTo(writer io.Writer) (int64, error) {
	reader, err := g.Generate()
	if err != nil {
		return 0, err
	}
	return io.Copy(writer, reader)
}

func NewGenerator(impl Implement) *Generator {
	return &Generator{impl: impl}
}
